sensor_embedding:
  _target_: torch.nn.Embedding
  num_embeddings: ${num_tokens_total}
  embedding_dim: ${embedding_dim}

sensor_tokenizers:
  _target_: torch.nn.ModuleDict
  modules:
    VehicleMotion_speed:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: cargpt.norm.MinMaxScaler
          in_range: ${speed_range}
          out_range: [0.0, 1.0]
        - _target_: torchaudio.transforms.MuLawEncoding
          quantization_channels: ${num_continous_tokens}
    VehicleMotion_gas_pedal_normalized:
      _target_: torchaudio.transforms.MuLawEncoding
      quantization_channels: ${num_continous_tokens}
    VehicleMotion_brake_pedal_normalized:
      _target_: torchaudio.transforms.MuLawEncoding
      quantization_channels: ${num_continous_tokens}
    VehicleMotion_steering_angle_normalized:
      _target_: torchaudio.transforms.MuLawEncoding
      quantization_channels: ${num_continous_tokens}
    VehicleState_turn_signal:
      _target_: torch.nn.Identity

sensor_detokenization:
  _target_: torch.nn.ModuleDict
  modules:
    VehicleMotion_speed:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: torchaudio.transforms.MuLawDecoding
          quantization_channels: ${num_continous_tokens}
        - _target_: cargpt.norm.Clamp
          min_value: 0.0
          max_value: 1.0
        - _target_: cargpt.norm.MinMaxScaler
          in_range: [0.0, 1.0]
          out_range: ${speed_range}
    VehicleMotion_gas_pedal_normalized:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: torchaudio.transforms.MuLawDecoding
          quantization_channels: ${num_continous_tokens}
        - _target_: cargpt.norm.Clamp
          min_value: 0.0
          max_value: 1.0
    VehicleMotion_brake_pedal_normalized:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: torchaudio.transforms.MuLawDecoding
          quantization_channels: ${num_continous_tokens}
        - _target_: cargpt.norm.Clamp
          min_value: 0.0
          max_value: 1.0
    VehicleMotion_steering_angle_normalized:
      _target_: torch.nn.Sequential
      _args_:
        - _target_: torchaudio.transforms.MuLawDecoding
          quantization_channels: ${num_continous_tokens}
        - _target_: cargpt.norm.Clamp
          min_value: -1.0
          max_value: 1.0
    VehicleState_turn_signal:
      _target_: torch.nn.Identity