#@yaml/text-templated-strings
---
_target_: rbyte.viz.loggers.RerunLogger
_convert_: all
_recursive_: false
application_id: prediction_policy
recording_name: [batch, meta, input_id]
port: 9877
schema:
  batch/cam_front_left/time_stamp:
    _target_: rerun.TimeColumn
    timestamp: [batch, data, meta/ImageMetadata.cam_front_left/time_stamp]
    dtype: datetime64[us]

  batch/cam_front_left/frame_idx:
    _target_: rerun.TimeColumn
    sequence: [batch, data, meta/ImageMetadata.cam_front_left/frame_idx]

  batch/cam_front_left:
    - _target_: rerun.Image.columns
      buffer: [batch, data, cam_front_left]

    - static: true
      entity:
        _target_: rerun.Image.from_fields
        format:
          _target_: rerun.components.ImageFormat
          height: 324
          width: 576
          color_model: RGB
          channel_datatype: u8

  #@ for key in [
  #@     "meta/VehicleMotion/brake_pedal_normalized",
  #@     "meta/VehicleMotion/gas_pedal_normalized",
  #@     "meta/VehicleMotion/steering_angle_normalized",
  #@     "meta/VehicleState/turn_signal",
  #@ ]:
  batch/(@=key@):
    - _target_: rerun.Scalars.columns
      scalars: [batch, data, (@=key@)]

    - static: true
      entity:
        _target_: rerun.SeriesLines
  #@ end

  #@ predictions = {
  #@     "policy": {
  #@         k: {"continuous": ["gas_pedal", "brake_pedal", "steering_angle"], "discrete": ["turn_signal"]}
  #@         for k in ["ground_truth", "prediction_value", "score_l1", "score_logprob"]
  #@     },
  #@ }
  #@ for key_objective, data_objective in predictions.items():
  #@  for key_prediction, data_prediction in data_objective.items():
  #@    for modality, keys in data_prediction.items():
  #@      for key in keys:
  (@=key_objective@)/(@=key_prediction@)/(@=modality@)/(@=key@):
    - _target_: rerun.Scalars.columns
      scalars:
        - (@=key_objective@)
        - (@=key_prediction@)
        - (@=modality@)
        - (@=key@)

    - static: true
      entity:
        _target_: rerun.SeriesLines
        names: (@=key_prediction@)/(@=key@)
  #@      end
  #@    end
  #@  end
  #@ end
