_target_: cargpt.models.control_transformer.ControlTransformer.load_from_wandb_artifact
artifact: ???
filename: model.ckpt
hparams_updaters:
  # 1. wrap hparams in DictConfig
  - _target_: omegaconf.DictConfig
    _partial_: true

  # 2. delete unnecesary keys
  - _target_: funcy.del_in
    _partial_: true
    path: ["objectives", "copycat", "streams", "policy", "losses"]

  # 3. merge config
  #  NOTE(galaxy brain alert): hydra instantiation with `_partial_: true` uses
  # `functools.partial`, which binds _leftmost_ positional arguments, which in this
  # case means the original hparams would be merged last, effectively negating any
  # updates. Using `funcy.rpartial` as a workaround.
  - _target_: funcy.rpartial
    _args_:
      - _target_: omegaconf.DictConfig.merge_with
        _partial_: true

      - _target_: omegaconf.DictConfig
        _recursive_: false
        content:
          objectives:
            copycat:
              policy:
                detokenizers:
                  _target_: cargpt.utils.ModuleDict
                  continuous:
                    gas_pedal:
                      _target_: cargpt.components.norm.UniformUnbinner
                      out_range: [0.0, 1.0]
                      num_bins: 255

                    brake_pedal:
                      _target_: cargpt.components.norm.UniformUnbinner
                      out_range: [0.0, 1.0]
                      num_bins: 165

                    steering_angle:
                      _target_: cargpt.components.norm.UniformUnbinner
                      out_range: [-1.0, 1.0]
                      num_bins: 961
