version: "3.3"

services:

  cargpt-gpu:
      build:
        context: .
        dockerfile: Dockerfile.gpu
        ssh:
          - default
      ipc: host
      runtime: nvidia
      # image: eu.gcr.io/yaak-ml-cloud/cargpt:gpu-latest
      volumes:
        - $HOME/cache:/root/.cache
        # output artifacts
        - ./lightning_logs:/home/yaak/lightning_logs
        - ./wandb:/home/yaak/wandb
        - ./output:/home/yaak/output
        - /nas:/nas
      ports:
        - "127.0.0.1:22910:22910"
      environment:
        - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
