# @package _global_

defaults:
  - /paths: default
  - /vars: control_transformer/default
  - /model: control_transformer/finetuned
  - /datamodule: predict
  - /loggers/rerun/prediction@rerun_logger
  - _self_

rerun_logger: ???

trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  accelerator: gpu
  devices: 1
  benchmark: true
  logger: false
  callbacks:
    - _target_: cargpt.callbacks.RerunPredictionWriter
      write_interval: batch
      logger: ${rerun_logger}

    - _target_: cargpt.callbacks.ModelSummary
      depth: 5
