# @package _global_

defaults:
  - /model: yaak/control_transformer/pretrained
  - /datamodule: yaak/predict
  - /paths: yaak/default
  - _self_

output_dir: ???

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  benchmark: true
  precision: "bf16-mixed"
  logger: false
  callbacks:
    - _target_: rmind.callbacks.TensorDictPredictionWriter
      write_interval: batch
      path: ${hydra:run.dir}/predictions/{batch_idx:06}/
      writer:
        _target_: tensordict.memmap
        _partial_: true
        copy_existing: true

    - _target_: rmind.callbacks.ModelSummary
      depth: 5
datamodule:
  predict:
    shuffle: true
