version: 2.1
orbs:
  python: circleci/python@2.1.1
executors:
  ci-runner:
    docker:
      - image: cimg/python:3.12.5
jobs:
  build:
    executor: ci-runner
    steps:
      - checkout
      - run: pip install --upgrade uv --no-cache-dir
      - run: uv sync --all-extras --locked
      - run: uv run ruff format --check
      - run: uv run ruff check --no-fix
      - run: uv run basedpyright
      - run: uv run pytest
      - run: uv run deptry . --ignore "DEP002"
workflows:
  main:
    jobs:
      - build
