_target_: cargpt.datamodules.GenericDataModule
train:
  _target_: torch.utils.data.DataLoader
  dataset: ???
  shuffle: true
  num_workers: 32
  pin_memory: true
  persistent_workers: true
  multiprocessing_context: fork
  collate_fn:
    _target_: yaak_datasets.collate
    _partial_: true

val:
  _target_: torch.utils.data.DataLoader
  dataset: ???
  shuffle: false
  num_workers: 32
  pin_memory: true
  persistent_workers: true
  multiprocessing_context: fork
  collate_fn:
    _target_: yaak_datasets.collate
    _partial_: true
