defaults:
  - /dataset/predict@predict.dataset
  - _self_

_target_: cargpt.datamodules.GenericDataModule
predict:
  _target_: torch.utils.data.DataLoader
  shuffle: false
  batch_size: ${vars.data.predict.batch_size}
  num_workers: 32
  pin_memory: false
  persistent_workers: true
  multiprocessing_context: forkserver
  collate_fn:
    _target_: rbyte.utils.dataloader.collate_identity
    _partial_: true
