"""The bimanual split lib, generated from nutron-cli's take-level split JSON.

    python -m rmind.scripts.nero_split_lib            # rewrite the lib from the copy
    python -m rmind.scripts.nero_split_lib --check    # exit 1 if the lib is stale
    python -m rmind.scripts.nero_split_lib --sync-from NUTRON_CLI_ROOT

ONE split for all four bimanual runs (two ACT, two patch): nutron-cli's
`runtime/training/make_split.py` writes `runtime/training/splits/<name>.json`
(schema `nutron_take_split/1`, stratified by active arm, every take's class
recorded). rmind keeps a byte-identical copy in `config/splits/<name>.json`
(`--sync-from` refreshes it; `tests/test_nero_bimanual.py` pins the copy against
a nutron-cli checkout when one is reachable) and renders it into the ytt lib
`config/_templates/dataset/nero/robot_bimanual_split.lib.yml` that the
`robot_bimanual_{train,val}` dataset templates load. The lib is GENERATED: never
edit it by hand. The arm-selection callback reads the take classes from the same
JSON copy.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[3]
SPLIT_NAME = "nero_cube_bimanual_v1"
SPLIT_JSON = REPO / "config" / "splits" / f"{SPLIT_NAME}.json"
SPLIT_LIB = (
    REPO / "config" / "_templates" / "dataset" / "nero" / "robot_bimanual_split.lib.yml"
)
NUTRON_CLI_SPLIT = Path("runtime") / "training" / "splits" / f"{SPLIT_NAME}.json"
SCHEMA = "nutron_take_split/1"
CLASSES = ("left", "right", "both")


def load_split(path: Path = SPLIT_JSON) -> dict[str, Any]:
    """Read and validate a `nutron_take_split/1` JSON.

    Raises:
        ValueError: on a wrong schema, overlapping or unknown takes, or a class
            missing from val.
    """
    split = json.loads(path.read_text(encoding="utf-8"))
    if split.get("schema") != SCHEMA:
        msg = f"{path}: schema {split.get('schema')!r}, expected {SCHEMA!r}"
        raise ValueError(msg)
    train, val, takes = list(split["train"]), list(split["val"]), split["takes"]
    if set(train) & set(val):
        msg = f"{path}: train and val share takes {sorted(set(train) & set(val))}"
        raise ValueError(msg)
    if len(set(train)) != len(train) or len(set(val)) != len(val):
        msg = f"{path}: duplicate takes in a split list"
        raise ValueError(msg)
    if set(train) | set(val) != set(takes):
        msg = f"{path}: train + val != the takes table"
        raise ValueError(msg)
    for name in train + val:
        want = "train" if name in set(train) else "val"
        if takes[name]["split"] != want or takes[name]["class"] not in CLASSES:
            msg = f"{path}: take {name} table entry {takes[name]} disagrees ({want})"
            raise ValueError(msg)
    val_classes = {takes[name]["class"] for name in val}
    if not {"left", "right"} <= val_classes:
        msg = f"{path}: val must hold both one-arm classes, has {sorted(val_classes)}"
        raise ValueError(msg)
    return split


def take_classes(path: Path = SPLIT_JSON) -> dict[str, str]:
    """take directory name -> active-arm class (left | right | both)."""
    return {name: t["class"] for name, t in load_split(path)["takes"].items()}


def _starlark_list(name: str, values: list[str]) -> list[str]:
    return [f"#@ {name} = [", *(f'#@     "{v}",' for v in values), "#@ ]"]


def render(path: Path = SPLIT_JSON) -> str:
    """The ytt lib text for the split JSON at `path` (deterministic)."""
    split = load_split(path)
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    counts = split["counts"]["by_class"]
    per_class = ", ".join(
        f"{c} {counts[c]['train']}/{counts[c]['val']}" for c in CLASSES if c in counts
    )
    lines = [
        "#@ # GENERATED by `python -m rmind.scripts.nero_split_lib` -- do not edit.",
        f"#@ # source: config/splits/{path.name} (sha256 {digest}),",
        f"#@ # a byte copy of nutron-cli {NUTRON_CLI_SPLIT.as_posix()}",
        "#@ # (the SAME take-level split the ACT runs use via train_sources/val_sources).",
        (
            f"#@ # {len(split['train'])} train / {len(split['val'])} val takes, "
            f"stratified by active arm (train/val: {per_class})."
        ),
        *_starlark_list("train", list(split["train"])),
        *_starlark_list("val", list(split["val"])),
    ]
    return "\n".join(lines) + "\n"


def nutron_cli_split(root: str | os.PathLike[str] | None = None) -> Path | None:
    """The split JSON in a nutron-cli checkout (`root`, else $NUTRON_CLI_ROOT), if any."""
    root = root or os.environ.get("NUTRON_CLI_ROOT")
    if not root:
        return None
    path = Path(root) / NUTRON_CLI_SPLIT
    return path if path.is_file() else None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the lib is stale")
    parser.add_argument(
        "--sync-from",
        metavar="NUTRON_CLI_ROOT",
        help="first copy the split JSON from this nutron-cli checkout",
    )
    args = parser.parse_args()
    if args.sync_from:
        source = nutron_cli_split(args.sync_from)
        if source is None:
            print(f"no {NUTRON_CLI_SPLIT} under {args.sync_from}", file=sys.stderr)  # noqa: T201
            return 1
        load_split(source)
        SPLIT_JSON.parent.mkdir(parents=True, exist_ok=True)
        SPLIT_JSON.write_bytes(source.read_bytes())
    text = render(SPLIT_JSON)
    if args.check:
        if not SPLIT_LIB.is_file() or SPLIT_LIB.read_text() != text:
            print(f"{SPLIT_LIB} is stale: rerun nero_split_lib", file=sys.stderr)  # noqa: T201
            return 1
        return 0
    SPLIT_LIB.write_text(text)
    print(f"wrote {SPLIT_LIB}")  # noqa: T201
    return 0


if __name__ == "__main__":
    sys.exit(main())
