_target_: rmind.models.control_transformer.ControlTransformer.load_from_wandb_artifact
artifact: ???
strict: false
hparams_updaters:
  # wrap hparams in DictConfig
  - _target_: omegaconf.DictConfig
    _partial_: true
  # override objectives to only use copycat/policy
  - _target_: omegaconf.OmegaConf.update
    _partial_: true
    _recursive_: false
    merge: false
    key: objectives
    value:
      _target_: rmind.components.containers.ModuleDict
      modules:
        policy:
          _target_: rmind.components.objectives.PolicyObjective
          heads:
            _target_: rmind.components.containers.ModuleDict
            modules:
              continuous:
                gas_pedal:
                  _target_: torchvision.ops.MLP
                  in_channels: 1152
                  hidden_channels:
                    - 384
                    - ${gas_pedal_bins}
                  bias: False
                brake_pedal:
                  _target_: torchvision.ops.MLP
                  in_channels: 1152
                  hidden_channels:
                    - 384
                    - ${brake_pedal_bins}
                  bias: False
                steering_angle:
                  _target_: torchvision.ops.MLP
                  in_channels: 1152
                  hidden_channels:
                    - 384
                    - ${steering_angle_bins}
                  bias: False
              discrete:
                turn_signal:
                  _target_: torchvision.ops.MLP
                  in_channels: 1152
                  hidden_channels: [384,3]
                  bias: False

          output_tokenizers:
            _target_: rmind.components.containers.ModuleDict
            modules:
              continuous:
                gas_pedal:
                  _target_: rmind.components.norm.UniformBinner
                  range: [0.0, 1.0]
                  bins: ${gas_pedal_bins}
                brake_pedal:
                  _target_: rmind.components.norm.UniformBinner
                  range: [0.0, 1.0]
                  bins: ${brake_pedal_bins}
                steering_angle:
                  _target_: rmind.components.norm.UniformBinner
                  range: [-1.0, 1.0]
                  bins: ${steering_angle_bins}
              discrete:
                _target_: rmind.components.nn.Identity

          targets:
            continuous:
              gas_pedal: [input_tokens, continuous, gas_pedal]
              brake_pedal: [input_tokens, continuous, brake_pedal]
              steering_angle: [input_tokens, continuous, steering_angle]
            discrete:
              turn_signal: [input_tokens, discrete, turn_signal]

          losses:
            _target_: rmind.components.containers.ModuleDict
            modules:
              continuous:
                gas_pedal:
                  _target_: rmind.components.loss.LogitBiasCrossEntropyLoss
                brake_pedal:
                  _target_: rmind.components.loss.LogitBiasCrossEntropyLoss
                steering_angle:
                  _target_: rmind.components.loss.LogitBiasCrossEntropyLoss
              discrete:
                turn_signal:
                  _target_: rmind.components.loss.LogitBiasCrossEntropyLoss

  # for some reason lr_scheduler.scheduler isn't checkpointed? re-add
  - _target_: omegaconf.OmegaConf.update
    _partial_: true
    _recursive_: false
    merge: false
    key: lr_scheduler
    value:
      interval: step
      scheduler:
        _target_: rmind.components.lr_schedulers.get_cosine_schedule_with_warmup
        num_warmup_steps: 25000
        num_training_steps: 250000
