---
_target_: rmind.models.control_transformer.ControlTransformer.load_from_wandb_artifact
artifact: ???
strict: false
hparams_jq: |
  .objectives = {
    "_target_": "rmind.components.containers.ModuleDict",
    "modules": {
      "policy": {
        "_target_": "rmind.components.objectives.PolicyObjective",
        "history_steps": 5,
        "action_horizon": 6,
        "feature_keys": [
          ["summary", "observation_summary"],
          ["context", "waypoints"],
          ["continuous", "speed"]
        ],
        "norm": {
          "_target_": "torch.nn.LayerNorm",
          "normalized_shape": 384
        },
        "heads": {
          "_target_": "rmind.components.containers.ModuleDict",
          "modules": {
            "continuous": {
              "gas_pedal": {
                "_target_": "rmind.components.nn.GRUHead",
                "in_features": 1152,
                "hidden_size": 384,
                "out_features": 2,
                "num_steps": 6
              },
              "brake_pedal": {
                "_target_": "rmind.components.nn.GRUHead",
                "in_features": 1152,
                "hidden_size": 384,
                "out_features": 2,
                "num_steps": 6
              },
              "steering_angle": {
                "_target_": "rmind.components.nn.GRUHead",
                "in_features": 1152,
                "hidden_size": 384,
                "out_features": 2,
                "num_steps": 6
              }
            },
            "discrete": {
              "turn_signal": {
                "_target_": "rmind.components.nn.GRUHead",
                "in_features": 1152,
                "hidden_size": 384,
                "out_features": 3,
                "num_steps": 6
              }
            }
          }
        },
        "targets": {
          "continuous": {
            "gas_pedal": ["input", "continuous", "gas_pedal"],
            "brake_pedal": ["input", "continuous", "brake_pedal"],
            "steering_angle": ["input", "continuous", "steering_angle"]
          },
          "discrete": {
            "turn_signal": ["input", "discrete", "turn_signal"]
          }
        },
        "trajectory_head": {
          "_target_": "rmind.components.nn.GRUTrajectoryHead",
          "in_features": 1152,
          "hidden_size": 384,
          "num_steps": 6
        },
        "trajectory_loss": {
          "_target_": "rmind.components.loss.GaussianNLLLoss"
        },
        "trajectory_loss_weight": ${trajectory_loss_weight},
        "xy_key": ["input", "trajectory", "xy"],
        "heading_key": ["input", "trajectory", "heading"],
        "losses": {
          "_target_": "rmind.components.containers.ModuleDict",
          "modules": {
            "continuous": {
              "gas_pedal": {
                "_target_": "rmind.components.loss.GaussianNLLLoss"
              },
              "brake_pedal": {
                "_target_": "rmind.components.loss.GaussianNLLLoss"
              },
              "steering_angle": {
                "_target_": "rmind.components.loss.GaussianNLLLoss"
              }
            },
            "discrete": {
              "turn_signal": {
                "_target_": "rmind.components.loss.LogitBiasCrossEntropyLoss"
              }
            }
          }
        }
      }
    }
  }
  | .episode_builder.input_transform._args_[0].paths.trajectory = {
    "xy": ["data", "meta/Gnss/xy"],
    "heading": ["data", "headings_denoised/heading"]
  }
  | .episode_builder.input_transform._args_[1].modules.trajectory = {
    "_target_": "torch.nn.Identity"
  }
  | .lr_scheduler = {
    "interval": "step",
    "scheduler": {
      "_target_": "rmind.components.lr_schedulers.get_cosine_schedule_with_warmup",
      "num_warmup_steps": 25000,
      "num_training_steps": 250000
    }
  }
