---
_target_: rmind.models.control_transformer.ControlTransformer.load_from_wandb_artifact
artifact: ???
strict: false
hparams_jq: |
  .objectives = {
    "_target_": "rmind.components.containers.ModuleDict",
    "modules": {
      "policy": {
        "_target_": "rmind.components.objectives.PolicyObjective",
        "norm": {
          "_target_": "torch.nn.LayerNorm",
          "normalized_shape": 384
        },
        "heads": {
          "_target_": "rmind.components.containers.ModuleDict",
          "modules": {
            "continuous": {
              "gas_pedal": {
                "_target_": "torchvision.ops.MLP",
                "in_channels": 1152,
                "hidden_channels": [384, 384, 2],
                "bias": false
              },
              "brake_pedal": {
                "_target_": "torchvision.ops.MLP",
                "in_channels": 1152,
                "hidden_channels": [384, 384, 2],
                "bias": false
              },
              "steering_angle": {
                "_target_": "torchvision.ops.MLP",
                "in_channels": 1152,
                "hidden_channels": [384, 384, 2],
                "bias": false
              }
            },
            "discrete": {
              "turn_signal": {
                "_target_": "torchvision.ops.MLP",
                "in_channels": 1152,
                "hidden_channels": [384, 384, 3],
                "bias": false
              }
            }
          }
        },
        "targets": {
          "continuous": {
            "gas_pedal": ["input", "continuous", "gas_pedal"],
            "brake_pedal": ["input", "continuous", "brake_pedal"],
            "steering_angle": ["input", "continuous", "steering_angle"]
          },
          "discrete": {
            "turn_signal": ["input", "discrete", "turn_signal"]
          }
        },
        "losses": {
          "_target_": "rmind.components.containers.ModuleDict",
          "modules": {
            "continuous": {
              "gas_pedal": {
                "_target_": "rmind.components.loss.GaussianNLLLoss"
              },
              "brake_pedal": {
                "_target_": "rmind.components.loss.GaussianNLLLoss"
              },
              "steering_angle": {
                "_target_": "rmind.components.loss.GaussianNLLLoss"
              }
            },
            "discrete": {
              "turn_signal": {
                "_target_": "rmind.components.loss.LogitBiasCrossEntropyLoss"
              }
            }
          }
        }
      }
    }
  }
  | .lr_scheduler = {
    "interval": "step",
    "scheduler": {
      "_target_": "rmind.components.lr_schedulers.get_cosine_schedule_with_warmup",
      "num_warmup_steps": 25000,
      "num_training_steps": 250000
    }
  }
  | walk(
      if type == "string" then
        if . == "rmind.components.waypoint_latent.WaypointLatentTokenizer"
        then "rmind.models.waypoints_tokenizer.WaypointsLatentTokenizer"
        elif . == "rmind.models.waypoint_tokenizer.WaypointTokenizer.load_from_wandb_artifact"
        then "rmind.models.waypoints_tokenizer.WaypointsTokenizer.load_from_wandb_artifact"
        else . end
      else . end
    )
