_target_: rmind.models.control_transformer.ControlTransformer.load_from_wandb_artifact
artifact: ???
filename: model.ckpt
hparams_jq: |
  delpaths([
    ["objectives", "inverse_dynamics", "losses"],
    ["objectives", "forward_dynamics", "losses"],
    ["objectives", "memory_extraction", "losses"]
  ])
