# @package _global_

defaults:
  - /model: carla_garage/control_transformer/finetuned
  - /datamodule: carla_garage/predict
  - /paths: carla_garage/default
  - /loggers/carla_garage/rerun/prediction@rerun_logger
  - _self_

rerun_logger: ???

trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  accelerator: gpu
  devices: 1
  benchmark: true
  logger: false
  callbacks:
    - _target_: cargpt.callbacks.RerunPredictionWriter
      write_interval: batch
      logger: ${rerun_logger}

    - _target_: cargpt.callbacks.ModelSummary
      depth: 5