batch_size: 1
clip_len: 3
patch_row_tokens: 32
patch_col_tokens: 60
local_position_tokens: 2000
total_tokens: 12294
tokens_shift: 4102
tokens_mask: 1
ignore_image_tokens: False
backbone:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: cargpt.models.encoding.dalleDVAE
      enc_weights: ${dalle_encoder_weights}
      freeze: True
    - _target_: cargpt.models.encoding.DVAEFeatures
      in_channels: 8192
      out_channels: ${embedding_dim}
      bias: False

loss:
  weights:
    ImageEncoder: 0.1

transforms:
  - _target_: yaak_datasets.transforms.Scale
    factor: 0.25

  - _target_: yaak_datasets.transforms.Crop
    offsets: [7, 7, 0, 0]

  - _target_: yaak_datasets.transforms.Normalize
    # https://github.com/openai/DALL-E/blob/master/dall_e/utils.py#L45
    mean: [-0.8, -0.8, -0.8]
    std: [1.25, 1.25, 1.25]