batch_size: 1
clip_len: 6
patch_row_tokens: 32
patch_col_tokens: 60
local_position_tokens: 2000
total_tokens: 12294
tokens_shift: 4102
tokens_mask: 1
ignore_image_tokens: False
backbone:
  _target_: cargpt.models.encoding.dalleDVAE
  enc_weights: ${dalle_encoder_weights}
  freeze: True
tokenizer:
  _target_: cargpt.models.encoding.DVAETokens

loss:
  weights:
    ImageEncoder: 0.8

transforms:

  - _target_: yaak_datasets.transforms.Scale
    factor: 0.84

  - _target_: yaak_datasets.transforms.Crop
    offsets: [8, 8, 1, 2]

  - _target_: yaak_datasets.transforms.Normalize
    # https://github.com/openai/DALL-E/blob/master/dall_e/utils.py#L45
    mean: [-0.125, -0.125, -0.125]
    std: [1.25, 1.25, 1.25]
