patch_row_tokens: 23
patch_col_tokens: 41
local_position_tokens: 945

seq_len: 5694
total_tokens: 4102
tokens_shift: 0
tokens_mask: -100

encoder:
  _target_: torch.nn.ModuleDict
  modules:
    dino:
      _target_: cargpt.models.encoding.DinoEncoder
      dino:
        _target_: torch.hub.load
        repo_or_dir: facebookresearch/dinov2
        model: dinov2_vits14

tokenizer:
  _target_: cargpt.models.encoding.ResNetTokens
  tokens_mask: ${..tokens_mask} # should match ignore_index in cross_entropy loss

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

transforms:
  - _target_: yaak_datasets.transforms.Crop
    offsets: [1, 1, 1, 1]

  - _target_: yaak_datasets.transforms.Normalize
    # ImageNet stats
    mean: ${...mean}
    std: ${...std}
