batch_size: 12
clip_len: 6
patch_row_tokens: 10
patch_col_tokens: 18
local_position_tokens: 256
max_seq_len: 2000
seq_len: 1116
total_tokens: 1030
tokens_shift: 0
tokens_mask: -100
speed_range: [0.0, 130.0]
frame_mask: [1, 1, 1, 1, 1, 1]
backbone:
  _target_: cargpt.models.encoding.ResnetBackbone
  resnet:
    _target_: torchvision.models.resnet18
    weights: IMAGENET1K_V1
  freeze: True
tokenizer:
  _target_: cargpt.models.encoding.ResNetTokens
  tokens_mask: ${..tokens_mask} # should match ignore_index in cross_entropy loss

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

transforms:

  - _target_: yaak_datasets.transforms.Crop
    offsets: [2, 2, 0, 0]

  - _target_: yaak_datasets.transforms.Normalize
    # ImageNet stats
    mean: ${...mean}
    std: ${...std}
