# @package _global_

defaults:
  - model: null
  - datamodule: null
  - trainer: null
  - experiment: null
  - _self_

wandb:
  entity: yaak
  project: cargpt
  settings:
    start_method: thread

seed: 1337
