data:
  train:
    batch_size: 4
    clip_length: 4
  val:
    batch_size: 8
    clip_length: 12
  test:
    clip_length: 24
  predict:
    batch_size: 1
encoder:
  num_heads: 2
  num_layers: 4
embedding_dim: 2048
