data:
  train:
    batch_size: 4
    clip_length: 6
  val:
    batch_size: 4
    clip_length: 6
  test:
    clip_length: 24
  predict:
    batch_size: 1
encoder:
  num_heads: 1
  num_layers: 1
embedding_dim: 2048
