# @package _global_

---
defaults:
  - /model: yaak/control_transformer/export/finetuned
  - /input: yaak/control_transformer/dummy
  - _self_

args:
  - ${input}

f: ${hydra:run.dir}/${model._target_}.onnx
artifacts_dir: ${hydra:run.dir}
