#@ drives = [
#@    'Niro104-HQ/2023-04-18--17-42-03',
#@    'Niro104-HQ/2023-04-06--06-52-49',
#@    'Niro104-HQ/2023-04-24--14-43-09',
#@    'Niro104-HQ/2023-04-27--08-23-53',
#@ ]
#@ cameras = ['cam_front_left']
#@

_target_: yaak_datasets.Dataset
_recursive_: false
config:
  version: 0.16.0
  data:
    drives:
      #@ for drive in drives:
      - id: #@ drive
        sources:
          #@ for camera in cameras:
          - camera: #@ camera
            reader:
              _target_: yaak_datasets.FrameImageVideoReader
              path: ${paths.data_dir}/${....id}/frames/${..camera}.defish.mp4/576x324/{:09d}.jpg
          #@ end
        metadata:
          path: ${paths.data_dir}/${..id}/metadata.log
      #@ end

    metadata:
      cameras: #@ cameras
      select:
        - message: ImageMetadata
          fields:
          - name: frame_idx
          - name: camera_name

        - message: VehicleMotion
          fields:
          - name: speed
          - name: steering_angle_normalized
          - name: gas_pedal_normalized
          - name: brake_pedal_normalized
          - name: acceleration_x
          - name: acceleration_y
          - name: acceleration_z

        - message: VehicleState
          fields:
          - name: turn_signal

        - message: Gnss
          fields:
          - name: hp_loc_latitude
          - name: hp_loc_longitude
  samples:
    alignment:
      ref_camera: #@ cameras[0]
      tolerance: 10ms

    clips:
      length: 1
      step: 1
      stride: 1

    transforms: ${image_encoder.transforms}

  processing:
    max_workers: null
    metadata:
      cache:
        enabled: true
        path: ${paths.metadata_cache_dir}
        size_limit: 1 GiB
