#@ drives = [
#@    'Niro115-HQ/2023-05-16--10-47-33',
#@    'Niro104-HQ/2022-12-20--13-57-20',
#@    'Niro107-HQ/2023-05-12--12-05-15',
#@    'Niro122-HQ/2023-04-05--12-06-39',
#@    'Niro102-HQ/2022-12-03--11-30-20',
#@ ]
#@ cameras = ['cam_front_left']
#@

_target_: yaak_datasets.Dataset
_recursive_: false
config:
  version: 0.16.1
  data:
    drives:
      #@ for drive in drives:
      - id: #@ drive
        sources:
          #@ for camera in cameras:
          - camera: #@ camera
            reader:
              _target_: yaak_datasets.FrameImageVideoReader
              path: ${paths.data_dir}/${....id}/frames/${..camera}.defish.mp4/576x324/{:09d}.jpg
            #! params: /nas/drives/yaak/yaak_dataset/camera_calibration/gamma/cam-90-deg/calib-pinhole-576x324.json
          #@ end
        metadata:
          path: ${paths.data_dir}/${..id}/metadata.log
      #@ end

    metadata:
      cameras: #@ cameras
      select: ???
      filter: ???

  samples:
    alignment:
      ref_camera: #@ cameras[0]
      tolerance: 10ms

    clips: ???
    transforms: ???

  processing:
    max_workers: null
    metadata:
      cache:
        enabled: true
        path: ${paths.metadata_cache_dir}
        size_limit: 1 GiB
