_target_: rbyte.Dataset
_recursive_: false
_convert_: all
inputs:
  Niro096-HQ/2023-01-11--13-47-36:
    frame:
      cam_front_left:
        index_column: ImageMetadata.cam_front_left.frame_idx
        reader:
          _target_: rbyte.io.frame.DirectoryFrameReader
          _recursive_: true
          path: ${paths.data_dir}/Niro096-HQ/2023-01-11--13-47-36/frames/cam_front_left.defish.mp4/576x324/{:09d}.jpg
          frame_decoder:
            _target_: simplejpeg.decode_jpeg
            _partial_: true
            colorspace: rgb
            fastdct: true
            fastupsample: true
    table:
      builder:
        _target_: rbyte.io.table.TableBuilder
        _convert_: all
        readers:
        - path: ${paths.data_dir}/Niro096-HQ/2023-01-11--13-47-36/metadata.log
          reader:
            _target_: rbyte.io.table.yaak.YaakMetadataTableReader
            _recursive_: false
            fields:
              rbyte.io.table.yaak.proto.sensor_pb2.ImageMetadata:
                time_stamp:
                  _target_: polars.Datetime
                  time_unit: ns
                frame_idx: polars.UInt32
                camera_name:
                  _target_: polars.Enum
                  categories:
                  - cam_front_center
                  - cam_front_left
                  - cam_front_right
                  - cam_left_forward
                  - cam_right_forward
                  - cam_left_backward
                  - cam_right_backward
                  - cam_rear
              rbyte.io.table.yaak.proto.can_pb2.VehicleState:
                time_stamp:
                  _target_: polars.Datetime
                  time_unit: ns
                turn_signal: polars.Int8
              rbyte.io.table.yaak.proto.can_pb2.VehicleMotion:
                time_stamp:
                  _target_: polars.Datetime
                  time_unit: ns
                speed: polars.Float32
                gas_pedal_normalized: polars.Float32
                brake_pedal_normalized: polars.Float32
                steering_angle_normalized: polars.Float32
                gear:
                  _target_: polars.Enum
                  categories:
                  - "0"
                  - "1"
                  - "2"
                  - "3"
        merger:
          _target_: rbyte.io.table.TableAligner
          separator: .
          merge:
            ImageMetadata.cam_front_left:
              time_stamp:
                method: ref
            VehicleState:
              time_stamp:
                method: ref
              turn_signal:
                method: asof
                tolerance: 100ms
            VehicleMotion:
              time_stamp:
                method: ref
              speed:
                method: interp
              gas_pedal_normalized:
                method: interp
              brake_pedal_normalized:
                method: interp
              steering_angle_normalized:
                method: interp
              gear:
                method: asof
                tolerance: 100ms
        filter: |
          `VehicleMotion.gear` == '3' and `VehicleMotion.speed` between 0.0 and 130.0 and `VehicleMotion.gas_pedal_normalized` between 0.0 and 1.0 and `VehicleMotion.brake_pedal_normalized` between 0.0 and 1.0 and `VehicleMotion.steering_angle_normalized` between -1.0 and 1.0
        cache:
          _target_: rbyte.utils.dataframe.DataframeDiskCache
          directory: ${paths.metadata_cache_dir}
          size_limit: 1GiB
sample_builder:
  _target_: rbyte.sample.builder.GreedySampleTableBuilder
  index_column: ImageMetadata.cam_front_left.frame_idx
  length: ${vars.data.train.clip_length}
  stride: 10
  min_step: 10
  filter: |-
    not (

          array_upper(`VehicleMotion.gas_pedal_normalized`) <= (1.0/255 + 0.001)
      and array_upper(`VehicleMotion.brake_pedal_normalized`) <= (1.0/164 + 0.001)
      and array_upper(`VehicleMotion.speed`) >= 25.0
      and array_get(`VehicleMotion.speed`, -1) - array_get(`VehicleMotion.speed`, 0) >= -0.05 * array_mean(`VehicleMotion.speed`)
    )
