_target_: yaak_datasets.Dataset
_recursive_: false
config:
  inputs:
    - id: Niro104-HQ/2023-04-18--17-42-03
      sources:
        frame:
          - id: cam_front_left
            index_column: "image_metadata.${.id}.frame_idx"
            reader:
              _target_: yaak_datasets.JpegFrameReader
              path: "${paths.data_dir}/${.....id}/frames/${..id}.defish.mp4/576x324/{:09d}.jpg"

        table:
          path: ${paths.data_dir}/${...id}/metadata.log
          builder:
            _target_: yaak_datasets.io.table.yaak.YaakMetadataTableBuilder
            _recursive_: false
            config:
              cameras: [cam_front_left]
              select:
                - message:
                    type: yaak_datasets.io.table.yaak.proto.sensor_pb2.ImageMetadata
                    alias: image_metadata
                  fields:
                    - name: time_stamp

                    - name: frame_idx
                      merge:
                        method: asof
                        tolerance: 10ms

                    - name: camera_name
                      partition: true

                - message:
                    type: yaak_datasets.io.table.yaak.proto.can_pb2.VehicleState
                    alias: vehicle_state
                  fields:
                    - name: time_stamp

                    - name: turn_signal
                      merge:
                        method: asof
                        tolerance: 100ms

                - message:
                    type: yaak_datasets.io.table.yaak.proto.can_pb2.VehicleMotion
                    alias: vehicle_motion
                  fields:
                    - name: time_stamp

                    - name: speed
                      merge:
                        method: interp

                    - name: gas_pedal_normalized
                      merge:
                        method: interp

                    - name: brake_pedal_normalized
                      merge:
                        method: interp

                    - name: steering_angle_normalized
                      merge:
                        method: interp

                    - name: gear
                      merge:
                        method: asof
                        tolerance: 100ms

              merge:
                reference:
                  key:
                    [
                      yaak_datasets.io.table.yaak.proto.sensor_pb2.ImageMetadata,
                      cam_front_left,
                    ]

                  column: time_stamp

              filter: >
                `vehicle_motion.gear` == 3
                and `vehicle_motion.speed` between 0.0 and 130.0
                and `vehicle_motion.gas_pedal_normalized` between 0.0 and 1.0
                and `vehicle_motion.brake_pedal_normalized` between 0.0 and 1.0
                and `vehicle_motion.steering_angle_normalized` between -1.0 and 1.0

              cache:
                _target_: yaak_datasets.utils.DataframeDiskCache
                directory: ${paths.metadata_cache_dir}
                size_limit: "10 GiB"
    #@ end
  samples:
    builder:
      _target_: yaak_datasets.dataset.sample.GreedySampleTableBuilder
      config:
        index_column: image_metadata.cam_front_left.frame_idx
        length: 6
        stride: 10
        min_step: 10
        filter: >
          not (
                array_upper(`vehicle_motion.gas_pedal_normalized`) <= (1.0/255 + 0.001)
            and array_upper(`vehicle_motion.brake_pedal_normalized`) <= (1.0/164 + 0.001)
            and array_upper(`vehicle_motion.speed`) >= 25.0
            and array_get(`vehicle_motion.speed`, -1) - array_get(`vehicle_motion.speed`, 0) >= -0.05 * array_mean(`vehicle_motion.speed`)
          )
