_target_: yaak_datasets.Dataset
_recursive_: false
config:
  version: 0.12.3
  data:
    drives:
    - id: Niro104-HQ/2022-12-20--13-57-20
      metadata:
        path: ${paths.data_dir}/${..id}/metadata.log
      sources:
      - camera: cam_front_left
        reader:
          _target_: yaak_datasets.FrameImageVideoReader
          filename_format: '{:09d}.jpg'
          path: ${paths.data_dir}/${....id}/frames/${..camera}.defish.mp4/576x324

    metadata:
      cameras:
      - cam_front_left

      select:
      - message: ImageMetadata
        fields:
        - name: frame_idx
        - name: camera_name

      - message: VehicleMotion
        fields:
        - name: speed
        - name: steering_angle_normalized
        - name: gas_pedal_normalized
        - name: brake_pedal_normalized

      - message: VehicleState
        fields:
        - name: turn_signal

  samples:
    alignment:
      ref_camera: cam_front_left
      tolerance: 10ms

    clips:
      length: 1
      stride: 1
      step: 1

    transforms: ${image_encoder.transforms}

  processing:
    max_workers: null
    metadata:
      cache:
        enabled: true
        path: ${paths.metadata_cache_dir}
        size_limit: 1 GiB
