_target_: yaak_datasets.Dataset
_recursive_: false
config:
  version: 0.12.0
  data:
    drives:
    - id: 2022-10-20--13-03-22
      sources:
      - camera: cam_front_right
        reader:
          _target_: yaak_datasets.FrameImageVideoReader
          path: ${paths.data_dir}/frames/${....id}/${..camera}.defish.mp4
          filename_format: '{:09d}.jpg'
      metadata:
        path: ${paths.data_dir}/frames/${..id}/metadata.log

    metadata:
      cameras:
      - cam_front_right

      select:
      - message: ImageMetadata
        fields:
        - name: frame_idx
        - name: camera_name

      - message: VehicleMotion
        fields:
        - name: speed
        - name: steering_angle_normalized
        - name: gas_pedal_normalized
        - name: brake_pedal_normalized

      - message: VehicleState
        fields:
        - name: turn_signal

      - message: Gnss
        fields:
        - name: hp_loc_latitude
        - name: hp_loc_longitude

  samples:
    alignment:
      ref_camera: cam_front_right
      tolerance: 10ms

    clips:
      length: 1
      stride: 1
      step: 1

    transforms:
      - _target_: yaak_datasets.transforms.Scale
        factor: 0.3

      - _target_: yaak_datasets.transforms.Crop
        offsets: [2, 2, 0, 0]

      - _target_: yaak_datasets.transforms.Normalize
        # ImageNet stats
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  processing:
    max_workers: null
    metadata:
      cache:
        enabled: true
        path: ${paths.metadata_cache_dir}
        size_limit: 1 GiB
