---
defaults:
  - /dataset/yaak/predict@predict.dataset
  - _self_

_target_: rmind.datamodules.GenericDataModule
predict:
  _target_: rbyte.dataloader.TorchDataNodeDataLoader
  batch_size: 16
  shuffle: false
  collate_fn:
    _target_: rmind.utils.functional.collate_batch
    _partial_: true

  num_workers: 2
  pin_memory: true
  method: thread
