---
defaults:
  - /dataset/yaak/val@train.dataset
  - /dataset/yaak/val@val.dataset
  - _self_

_target_: rmind.datamodules.GenericDataModule
train:
  _target_: rbyte.dataloader.TorchDataNodeDataLoader
  batch_size: 24
  shuffle: true
  collate_fn:
    _target_: rbyte.types.Batch.to_dict
    _partial_: true

  pin_memory: true
  num_workers: 2
  method: thread

val:
  _target_: rbyte.dataloader.TorchDataNodeDataLoader
  batch_size: 24
  shuffle: false
  collate_fn:
    _target_: rbyte.types.Batch.to_dict
    _partial_: true

  pin_memory: true
  num_workers: 2
  method: thread
