# @package _global_

defaults:
  - /paths: default
  - /image_encoder: dall_e.yaml
  - _self_

output_file: video.mp4
clip_len: 5

trainer:
  benchmark: true
  callbacks:
    - _target_: cargpt.callbacks.VideoWriter
      output_file: ${output_file}
      overwrite: true
      fourcc: mp4v
      fps: 30

model:
  _target_: cargpt.visualization.Frames
  _recursive_: False
  # Let the model be optional so that we can use both gt and preds
  inference_model:
    _target_: cargpt.models.gato.Gato.load_from_wandb_artifact
    _args_: ['yaak/cargpt/model-2hndnzr1:v5']

  image_decoder:
    _target_: cargpt.models.decoding.dalleDVAE
    dec_weights: pretrained/dalle/decoder.pkl
    vocab_size: 8192
    freeze: True

  future_timestep: 120
  patch_row: ${image_encoder.patch_row_tokens}
  patch_col: ${image_encoder.patch_col_tokens}

datamodule:
  _target_: cargpt.datamodules.GenericDataModule
  predict:
    _target_: torch.utils.data.DataLoader
    shuffle: false
    batch_size: 1
    num_workers: 8
    pin_memory: true
    persistent_workers: true
    multiprocessing_context: fork
    dataset:
      _target_: yaak_datasets.Dataset
      _recursive_: false
      config:
        version: 0.12.3
        data:
          drives:
          - id: Niro115-HQ/2023-05-16--10-47-33
            sources:
            - camera: cam_front_left
              reader:
                _target_: yaak_datasets.FrameImageVideoReader
                path: ${paths.data_dir}/${....id}/frames/${..camera}.defish.mp4/576x324
                filename_format: '{:09d}.jpg'
            metadata:
              path: ${paths.data_dir}/${..id}/metadata.log
              filter: ImageMetadata_frame_idx between 24900 and 25410  # TODO: remove

          metadata:
            cameras:
            - cam_front_left

            select:
            - message: ImageMetadata
              fields:
              - name: frame_idx
              - name: camera_name

            - message: VehicleMotion
              fields:
              - name: speed
              - name: steering_angle_normalized
              - name: brake_pedal_normalized
              - name: gas_pedal_normalized
            - message: VehicleState
              fields:
              - name: turn_signal

        samples:
          alignment:
            ref_camera: cam_front_left
            tolerance: 10ms

          clips:
            length: ${clip_len}
            stride: 10
            step: 1

          transforms:
            - _target_: yaak_datasets.transforms.Scale
              factor: 0.84

            - _target_: yaak_datasets.transforms.Crop
              offsets: [8, 8, 1, 2]

            - _target_: yaak_datasets.transforms.Normalize
              # https://github.com/openai/DALL-E/blob/master/dall_e/utils.py#L45
              mean: [-0.125, -0.125, -0.125]
              std: [1.25, 1.25, 1.25]

        processing:
          max_workers: null
          metadata:
            cache:
              enabled: true
              path: ${paths.metadata_cache_dir}
              size_limit: 1 GiB

    collate_fn:
      _target_: yaak_datasets.collate
      _partial_: true