# @package _global_

defaults:
  - /paths: default
  - /image_encoder: dall_e.yaml
  - _self_

run_id: lq29aa4q
version: v12
output_file: video-${run_id}-${version}.mp4
wandb_artifact: yaak/cargpt/model-${run_id}:${version}
clip_len: 3
speed_range: ${image_encoder.speed_range}

trainer:
  benchmark: true
  callbacks:
    - _target_: cargpt.callbacks.VideoWriter
      output_file: ${output_file}
      overwrite: true
      fourcc: mp4v
      fps: 30

model:
  _target_: cargpt.visualization.Frames
  _recursive_: False
  # Let the model be optional so that we can use both gt and preds
  inference_model:
    _target_: cargpt.models.gato.Gato.load_from_wandb_artifact
    _args_: ['${wandb_artifact}']
    strict: False

  image_decoder:
    _target_: cargpt.models.decoding.dalleDVAE
    dec_weights: pretrained/dalle/decoder.pkl
    vocab_size: 8192
    freeze: True

  future_timestep: 6
  patch_row: ${image_encoder.patch_row_tokens}
  patch_col: ${image_encoder.patch_col_tokens}

  logging:
    log_to_terminal: False
    smooth_predictions: False
    smooth_kernel_size: 7

datamodule:
  _target_: cargpt.datamodules.GenericDataModule
  predict:
    _target_: torch.utils.data.DataLoader
    shuffle: false
    batch_size: 1
    num_workers: 1
    pin_memory: false
    persistent_workers: true
    multiprocessing_context: forkserver
    dataset:
      _target_: yaak_datasets.Dataset
      _recursive_: false
      config:
        version: 0.13.1
        data:
          drives:
          - id: 2022-10-20--13-03-22
            sources:
            - camera: cam_front_left  # TODO: probably wanna front center, but extrinsics should also be fine
              # TODO: uncomment after yaak-datasets support calibration files
              # params: ${paths.data_dir}/calibration/gamma/cam-90-deg/calib-pinhole.json
              reader:
                _target_: yaak_datasets.FrameImageVideoReader
                path: ${paths.data_dir}/${....id}/frames/${..camera}.defish.mp4/576x324
                filename_format: '{:09d}.jpg'
            metadata:
              path: ${paths.data_dir}/${..id}/metadata.log
              filter: (ImageMetadata_frame_idx between 5550 and 5850) and
                      VehicleMotion_speed between ${speed_range[0]} and ${speed_range[1]}
          metadata:
            cameras:
            - cam_front_left

            select:
            - message: ImageMetadata
              fields:
              - name: frame_idx
              - name: camera_name

            - message: VehicleMotion
              fields:
              - name: speed
              - name: steering_angle_normalized
              - name: brake_pedal_normalized
              - name: gas_pedal_normalized
            - message: VehicleState
              fields:
              - name: turn_signal

        samples:
          alignment:
            ref_camera: cam_front_left
            tolerance: 10ms

          clips:
            length: ${clip_len}
            stride: 10
            step: 1

          transforms: ${image_encoder.transforms}

        processing:
          max_workers: null
          metadata:
            cache:
              enabled: true
              path: ${paths.metadata_cache_dir}
              size_limit: 1 GiB

    collate_fn:
      _target_: yaak_datasets.collate
      _partial_: true