# @package _global_

defaults:
  - /paths: default
  - /image_encoder: resnet.yaml
  - _self_

wandb:
  project: cargpt
  group: Gato-benchmarks
  dir: ./wandb-runs

run_id: wfzb5qvy
version: v17
output_file: score-${run_id}-${version}.json
overwrite: True
wandb_artifact: yaak/cargpt/model-${run_id}:${version}
incidents_file: /nas/drives/yaak/incidents/student.json
clip_len: 6

trainer:
  benchmark: true
  callbacks:
    - _target_: cargpt.callbacks.ScoreWriter
      incidents_file: ${incidents_file}
      output_file: ${output_file}
      overwrite: ${overwrite}
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: ${wandb.project}


model:
  _target_: cargpt.utils.SafetyScore
  _recursive_: False
  # Let the model be optional so that we can use both gt and preds
  inference_model:
    _target_: cargpt.models.gato.Gato.load_from_wandb_artifact
    _args_: ['${wandb_artifact}']
    strict: False

datamodule:
  _target_: cargpt.datamodules.GenericDataModule
  predict:
    _target_: torch.utils.data.DataLoader
    shuffle: false
    batch_size: 1
    num_workers: 1
    pin_memory: false
    persistent_workers: true
    multiprocessing_context: forkserver
    dataset:
      _target_: yaak_datasets.Dataset
      _recursive_: false
      config:
        version: 0.16.0
        data:
          drives:
          - id: Niro104-HQ/2023-04-18--17-42-03
            sources:
            - camera: cam_front_left
              reader:
                _target_: yaak_datasets.FrameImageVideoReader
                path: ${paths.data_dir}/${....id}/frames/${..camera}.defish.mp4/576x324/{:09d}.jpg
            metadata:
              path: ${paths.data_dir}/${..id}/metadata.log
              filter: (ImageMetadata_frame_idx between 24900 and 25310)

          metadata:
            cameras:
            - cam_front_left

            select:
            - message: ImageMetadata
              fields:
              - name: frame_idx
              - name: camera_name

            - message: VehicleMotion
              fields:
              - name: speed
              - name: steering_angle_normalized
              - name: brake_pedal_normalized
              - name: gas_pedal_normalized
            - message: VehicleState
              fields:
              - name: turn_signal

        samples:
          alignment:
            ref_camera: cam_front_left
            tolerance: 10ms

          clips:
            length: ${clip_len}
            stride: 10
            step: 1

          transforms: ${image_encoder.transforms}

        processing:
          max_workers: null
          metadata:
            cache:
              enabled: true
              path: ${paths.metadata_cache_dir}
              size_limit: 1 GiB

    collate_fn:
      _target_: yaak_datasets.collate
      _partial_: true
