# @package _global_

defaults:
  - /paths: default
  - /dataset/predict@datamodule.predict.dataset
  - _self_

batch_size: 64
clip_len: 6

speed_range: [5.0, 130.0]

model:
  _target_: cargpt.models.control_transformer.ControlTransformer.load_from_wandb_artifact
  artifact: ???
  filename: model.ckpt
  hparams_updaters:
    # 1. wrap hparams in DictConfig
    - _target_: omegaconf.DictConfig
      _partial_: true

    # 2. delete unnecesary keys
    - _target_: funcy.del_in
      _partial_: true
      path: ["objectives", "forward_dynamics", "heads", "image"]

    - _target_: funcy.del_in
      _partial_: true
      path: ["objectives", "copycat", "memory_extraction", "loss"]

    - _target_: funcy.del_in
      _partial_: true
      path: ["objective_scheduler"]

    # 3. merge config
    #  NOTE(galaxy brain alert): hydra instantiation with `_partial_: true` uses
    # `functools.partial`, which binds _leftmost_ positional arguments, which in this
    # case means the original hparams would be merged last, effectively negating any
    # updates. Using `funcy.rpartial` as a workaround.
    - _target_: funcy.rpartial
      _args_:
        - _target_: omegaconf.DictConfig.merge_with
          _partial_: true

        - _target_: omegaconf.DictConfig
          _recursive_: false
          content:
            episode_builder:
              detokenizers:
                _target_: cargpt.utils.ModuleDict
                continuous:
                  speed:
                    _target_: cargpt.components.norm.UniformUnbinner
                    out_range: ${speed_range}
                    num_bins: 1024

                  gas_pedal:
                    _target_: cargpt.components.norm.UniformUnbinner
                    out_range: [0.0, 1.0]
                    num_bins: 255

                  brake_pedal:
                    _target_: cargpt.components.norm.UniformUnbinner
                    out_range: [0.0, 1.0]
                    num_bins: 165

                  steering_angle:
                    _target_: cargpt.components.norm.UniformUnbinner
                    out_range: [-1.0, 1.0]
                    num_bins: 961

                discrete:
                  turn_signal:
                    _target_: torch.nn.Identity

            objectives:
              forward_dynamics:
                losses: null

              inverse_dynamics:
                losses: null

              random_masked_hindsight_control:
                losses: null

              copycat:
                memory_extraction:
                  delta_detokenizers:
                    _target_: cargpt.utils.ModuleDict
                    continuous:
                      gas_pedal:
                        _target_: torchaudio.transforms.MuLawDecoding
                        quantization_channels: 512

                      brake_pedal:
                        _target_: torchaudio.transforms.MuLawDecoding
                        quantization_channels: 512

                      steering_angle:
                        _target_: torch.nn.Sequential
                        _args_:
                          - _target_: torchaudio.transforms.MuLawDecoding
                            quantization_channels: 512

                          - _target_: cargpt.components.norm.Scaler
                            in_range: [-1.0, 1.0]
                            out_range: [-2.0, 2.0]

                  losses: null

datamodule:
  _target_: cargpt.datamodules.GenericDataModule
  predict:
    _target_: torch.utils.data.DataLoader
    shuffle: false
    batch_size: ${batch_size}
    num_workers: 32
    pin_memory: false
    persistent_workers: true
    multiprocessing_context: forkserver
    collate_fn:
      _target_: yaak_datasets.collate
      _partial_: true
    dataset:
      config:
        data:
          metadata:
            select:
              - message: ImageMetadata
                fields:
                  - name: frame_idx
                  - name: camera_name

              - message: VehicleMotion
                fields:
                  - name: speed
                    merge:
                      method: interp

                  - name: steering_angle_normalized
                    merge:
                      method: interp

                  - name: gas_pedal_normalized
                    merge:
                      method: interp

                  - name: brake_pedal_normalized
                    merge:
                      method: interp

              - message: VehicleState
                fields:
                  - name: turn_signal

            filter: >
              VehicleMotion_speed between ${speed_range[0]} and ${speed_range[1]}
              and VehicleMotion_gas_pedal_normalized between 0.0 and 1.0
              and VehicleMotion_brake_pedal_normalized between 0.0 and 1.0
              and VehicleMotion_steering_angle_normalized between -1.0 and 1.0
              and (VehicleMotion_gas_pedal_normalized > 0.0 or VehicleMotion_brake_pedal_normalized > 0.0)

        samples:
          clips:
            length: ${clip_len}
            stride: 10
            step: 60 # NOTE

          transforms:
            - _target_: yaak_datasets.transforms.Crop
              offsets: [2, 2, 0, 0]

            - _target_: yaak_datasets.transforms.Normalize
              # ImageNet stats
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: [1]
  benchmark: true
  logger: false

  callbacks:
    - _target_: cargpt.callbacks.model_summary.ModelSummary
      depth: 5

    - _target_: cargpt.callbacks.rerun.RerunPredictionWriter
      write_interval: batch
      application_id: ${model.artifact}
