# @package _global_

defaults:
  - /paths: default
  - /model: control_transformer/finetuned
  - /dataset/predict@datamodule.predict.dataset
  - _self_

vars:
  batch_size: 64
  clip_len: 6
  speed_range: [0.0, 130.0]
  embedding_dim: 512

datamodule:
  _target_: cargpt.datamodules.GenericDataModule
  predict:
    _target_: torch.utils.data.DataLoader
    shuffle: false
    batch_size: ${vars.batch_size}
    num_workers: 32
    pin_memory: false
    persistent_workers: true
    multiprocessing_context: forkserver
    collate_fn:
      _target_: yaak_datasets.utils.dataloader.collate_identity
      _partial_: true

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  benchmark: true
  logger: false

  callbacks:
    - _target_: cargpt.callbacks.model_summary.ModelSummary
      depth: 5

    - _target_: cargpt.callbacks.rerun.RerunPredictionWriter
      write_interval: batch
      application_id: ${model.artifact}
