# @package _global_

defaults:
  - /paths: default
  - /image_encoder: dall_e.yaml
  - _self_

run_id: 0jvqpv0k
version: v15
output_file: video-${run_id}-${version}.mp4
wandb_artifact: yaak/cargpt/model-${run_id}:${version}
clip_len: 6

trainer:
  benchmark: false
  callbacks:
    - _target_: cargpt.callbacks.VideoWriter
      output_file: ${output_file}
      overwrite: true
      fourcc: mp4v
      fps: 30

model:
  _target_: cargpt.visualization.Trajectory
  _recursive_: False
  # Let the model be optional so that we can use both gt and preds
  inference_model:
    _target_: cargpt.models.gato.Gato.load_from_wandb_artifact
    _args_: ['${wandb_artifact}']
    strict: False

  ground_truth_trajectory:
    steps: 30
    time_interval: 0.1  # [s]

  images_transform:
    _target_: cargpt.visualization.Unnormalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

  car:
    wheelbase: 2.7  # [m], 2700 [mm]
    max_beta: 35.75  # [deg]  # TODO: find the real middle beta

  logging:
    log_to_terminal: False
    smooth_predictions: False
    smooth_kernel_size: 7

datamodule:
  _target_: cargpt.datamodules.GenericDataModule
  predict:
    _target_: torch.utils.data.DataLoader
    shuffle: false
    batch_size: 1
    num_workers: 8
    pin_memory: false
    persistent_workers: true
    multiprocessing_context: forkserver
    dataset:
      _target_: yaak_datasets.Dataset
      _recursive_: false
      config:
        version: 0.16.0
        data:
          drives:
          - id: 2022-10-20--13-03-22
            sources:
            - camera: cam_front_left  # TODO: probably wanna front center, but extrinsics should also be fine
              reader:
                _target_: yaak_datasets.FrameImageVideoReader
                path: ${paths.data_dir}/frames/${....id}/${..camera}.defish.mp4/{:09d}.jpg
            metadata:
              path: ${paths.data_dir}/frames/${..id}/metadata.log
              filter: (ImageMetadata_frame_idx between 24900 and 25310)

              # filter: (ImageMetadata_frame_idx between 5610 and 5930) or
              #         (ImageMetadata_frame_idx between 11030 and 12020) or
              #         (ImageMetadata_frame_idx between 22560 and 22860) or
              #         (ImageMetadata_frame_idx between 24900 and 25310)

          metadata:
            cameras:
            - cam_front_left

            select:
            - message: ImageMetadata
              fields:
              - name: frame_idx
              - name: camera_name

            - message: VehicleMotion
              fields:
              - name: speed
              - name: steering_angle_normalized
              - name: brake_pedal_normalized
              - name: gas_pedal_normalized
              - name: acceleration_x
              - name: acceleration_y
              - name: acceleration_z
            - message: VehicleState
              fields:
              - name: turn_signal

        samples:
          alignment:
            ref_camera: cam_front_left
            tolerance: 10ms

          clips:
            length: ${clip_len}
            stride: 10
            step: 1

          transforms:
            - _target_: yaak_datasets.transforms.Scale
              factor: 0.3

            - _target_: yaak_datasets.transforms.Crop
              offsets: [2, 2, 0, 0]

            - _target_: yaak_datasets.transforms.Normalize
              # ImageNet stats
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]

        processing:
          max_workers: null
          metadata:
            cache:
              enabled: true
              path: ${paths.metadata_cache_dir}
              size_limit: 1 GiB

    collate_fn:
      _target_: yaak_datasets.collate
      _partial_: true
