# @package _global_

defaults:
  - /paths: default
  - _self_

output_file: ???
batch_size: ???
clip_len: ???

trainer:
  callbacks:
    - _target_: cargpt.callbacks.VideoWriter
      output_file: ${output_file}
      overwrite: false
      fourcc: vp09
      fps: 30

model:
  _target_: cargpt.utils.visualization.CILppWrapper
  _recursive_: False
  model:
    _target_: cargpt.models.cilpp.CILpp.load_from_wandb_artifact
    _args_: ['yaak/cargpt/model-0mbtfm8x:v0']
  # The convolution layer to take for visualization, when multiple - mean is used
  visualize_layers:
    - model.state_embedding['frame']['backbone'].resnet.layer4[-1]
  images_transform:
    _target_: cargpt.utils.visualization.Unnormalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  labels:
    cv2_font: FONT_HERSHEY_SIMPLEX
    font_scale: 1
    font_color: [255, 255, 255]
    font_thickness: 2
  # Pick RawAccelerationTarget or RawSteeringTarget
  visualize_target:
    _target_: cargpt.utils.visualization.RawAccelerationTarget

datamodule:
  _target_: cargpt.datamodules.GenericDataModule
  predict:
    _target_: torch.utils.data.DataLoader
    shuffle: false
    batch_size: ${batch_size}
    num_workers: 8
    pin_memory: true
    persistent_workers: true
    multiprocessing_context: fork
    dataset:
      _target_: yaak_datasets.Dataset
      _recursive_: false
      config:
        version: 0.11.1
        data:
          drives:
          - id: 2022-10-20--13-03-22
            sources:
            - camera: cam_front_right
              reader:
                _target_: yaak_datasets.FrameImageVideoReader
                path: ${paths.data_dir}/frames/${....id}/${..camera}.defish.mp4
                filename_format: '{:09d}.jpg'
            metadata:
              path: ${paths.data_dir}/frames/${..id}/metadata.log

          metadata:
            cameras:
            - cam_front_right

            select:
            - message: ImageMetadata
              fields:
              - name: frame_idx
              - name: camera_name

            - message: VehicleMotion
              fields:
              - name: speed
              - name: steering_angle_normalized
              - name: gas_pedal_normalized
              - name: brake_pedal_normalized

            - message: VehicleState
              fields:
              - name: turn_signal

            filter: VehicleMotion_speed between 8 and 40

        samples:
          alignment:
            ref_camera: cam_front_right
            tolerance: 10ms

          clips:
            length: ${clip_len}
            stride: 1
            step: 1

          transforms:
            - _target_: yaak_datasets.transforms.Scale
              factor: 0.3

            - _target_: yaak_datasets.transforms.Crop
              offsets: [2, 2, 0, 0]

            - _target_: yaak_datasets.transforms.Normalize
              # ImageNet stats
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]

        processing:
          max_workers: null
          metadata_cache:
            enabled: true
            path: ${paths.metadata_cache_dir}
            size_limit: 1 GiB

    collate_fn:
      _target_: yaak_datasets.collate
      _partial_: true
