#@yaml/text-templated-strings

#@ drives = [
#@     'YieldToEmergencyVehicle',
#@ ]

#@ cameras = [
#@     'cam_front_left',
#@ ]
---
_target_: rbyte.Dataset
_recursive_: false
_convert_: all
inputs:
  #@ for input_id in drives:
  (@=input_id@):
    sources:
      #@ for source_id in cameras:
      (@=source_id@):
        index_column: _idx_
        source:
          _target_: rbyte.io.PathTensorSource
          path: "${paths.data_dir}/(@=input_id@)/frames/(@=source_id@).defish.mp4/576x324/{:09d}.jpg"
          decoder:
            _target_: simplejpeg.decode_jpeg
            _partial_: true
            colorspace: rgb
            fastdct: true
            fastupsample: true

      #@ end

    samples:
      pipeline:
        _target_: pipefunc.Pipeline
        validate_type_annotations: false
        functions:
          - _target_: pipefunc.PipeFunc
            bound:
              path: ${paths.data_dir}/(@=input_id@)/ego_logs.json
            output_name: ego_logs
            func:
              _target_: rbyte.io.JsonDataFrameBuilder
              fields:
                records:
                  control.brake:
                  control.throttle:
                  control.steer:
                  state.velocity.value:
                  state.acceleration.value:
                  state.transform.x:
                  state.transform.y:

          - _target_: pipefunc.PipeFunc
            renames:
              input: ego_logs
            output_name: data
            func:
              _target_: rbyte.io.DataFrameConcater
              method: vertical

          - _target_: pipefunc.PipeFunc
            renames:
              input: data
            output_name: data_resampled
            func:
              _target_: rbyte.io.DataFrameFpsResampler
              fps_in: 20
              fps_out: 30

          - _target_: pipefunc.PipeFunc
            renames:
              input: data_resampled
            output_name: data_indexed
            func:
              _target_: rbyte.io.DataFrameIndexer
              name: _idx_
                
          - _target_: pipefunc.PipeFunc
            renames:
              input: data_indexed
            output_name: data_merged
            func:
              _target_: rbyte.io.dataframe.waypoints_merger.DataFrameWaypointsMerger
              waypoints_path: ${paths.data_dir}/(@=input_id@)/waypoints.json
              coordinates_type: xy
              ego_lon_x_col: state.transform.x
              ego_lat_y_col: state.transform.y
              timestamp_col: _idx_
              num_waypoints: 10
              out_col: Waypoints.xy
              predict_mode: true

          - _target_: pipefunc.PipeFunc
            renames:
              input: data_merged
            output_name: samples
            func:
              _target_: rbyte.FixedWindowSampleBuilder
              index_column: _idx_
              every: 10i
              period: 110i
              closed: both
              gather_every: 10
              length: 12
  #@ end
