#@yaml/text-templated-strings

#@ drives = [
#@  'ConstructionObstacleTwoWays/Town12_Rep0_1561_0_route0_11_08_10_20_42',
#@  'StaticCutIn/Town12_Rep0_1004_0_route0_11_08_09_19_22',
#@  'ParkingExit/Town12_Rep0_2667_0_route0_11_08_22_17_50',
#@  'HazardAtSideLane/Town12_Rep0_3190_0_route0_11_09_09_04_10',
#@  'HazardAtSideLaneTwoWays/Town12_Rep0_409_0_route0_11_08_07_30_55',
#@  'HighwayExit/Town12_Rep0_4136_7_route0_11_08_13_37_51',
#@  'ControlLoss/Town12_Rep0_2691_0_route0_11_09_10_54_37',
#@  'HazardAtSideLaneTwoWays/Town12_Rep0_498_0_route0_11_09_00_52_10',
#@  'ParkingCrossingPedestrian/Town12_Rep0_1710_0_route0_11_08_10_45_37',
#@  'Accident/Town12_Rep0_2478_0_route0_11_07_23_56_01',
#@  'Accident/Town12_Rep0_4117_0_route0_11_09_02_00_41',
#@  'HardBreakRoute/Town12_Rep0_2630_0_route0_11_08_15_23_12',
#@  'NonSignalizedJunctionLeftTurn/Town12_Rep0_262_1_route0_11_08_16_26_29',
#@  'OppositeVehicleTakingPriority/Town12_Rep0_336_1_route0_11_08_23_32_37',
#@  'InterurbanActorFlow/Town12_Rep0_427_6_route0_11_09_00_08_29',
#@  'Accident/Town12_Rep0_2232_0_route0_11_08_12_43_45',
#@  'EnterActorFlowV2/Town12_Rep0_2509_10_route0_11_09_07_35_48',
#@  'MergerIntoSlowTrafficV2/Town12_Rep0_968_4_route0_11_07_23_33_42',
#@  'PriorityAtJunction/Town12_Rep0_1114_0_route0_11_08_19_13_32',
#@  'ConstructionObstacle/Town12_Rep0_4098_0_route0_11_09_01_36_33',
#@  'HazardAtSideLaneTwoWays/Town12_Rep0_2833_0_route0_11_08_21_33_53',
#@  'ParkingCrossingPedestrian/Town12_Rep0_4170_0_route0_11_08_20_08_06',
#@  'ConstructionObstacleTwoWays/Town12_Rep0_3581_1_route0_11_08_10_04_40',
#@  'DynamicObjectCrossing/Town12_Rep0_2305_0_route0_11_08_10_52_05',
#@  'EnterActorFlowV2/Town12_Rep0_2509_7_route0_11_09_11_03_04',
#@  'Accident/Town12_Rep0_2882_0_route0_11_08_15_54_31',
#@  'ConstructionObstacle/Town12_Rep0_2508_0_route0_11_08_07_59_02',
#@  'HazardAtSideLaneTwoWays/Town12_Rep0_3067_0_route0_11_07_23_21_03',
#@  'HazardAtSideLane/Town12_Rep0_3988_0_route0_11_08_21_02_54',
#@  'Accident/Town12_Rep0_3990_1_route0_11_09_06_54_24',
#@  'HighwayCutIn/Town12_Rep0_4016_0_route0_11_08_03_47_29',
#@  'PedestrianCrossing/Town12_Rep0_860_1_route0_11_08_00_38_47',
#@  'VehicleTurningRoute/Town12_Rep0_3356_0_route0_11_08_22_12_50',
#@  'ConstructionObstacle/Town12_Rep0_643_0_route0_11_09_03_12_21',
#@  'VehicleTurningRoutePedestrian/Town12_Rep0_261_0_route0_11_08_09_28_20',
#@  'HighwayCutIn/Town12_Rep0_1394_3_route0_11_08_14_06_59',
#@  'OppositeVehicleTakingPriority/Town12_Rep0_3106_1_route0_11_08_13_03_54',
#@  'ParkedObstacle/Town12_Rep0_4028_0_route0_11_08_03_09_28',
#@  'MergerIntoSlowTraffic/Town12_Rep0_1010_1_route0_11_08_13_44_35',
#@  'OppositeVehicleRunningRedLight/Town12_Rep0_2813_0_route0_11_08_09_01_39',
#@  'CrossingBicycleFlow/Town12_Rep0_684_1_route0_11_08_03_22_42',
#@  'InvadingTurn/Town12_Rep0_55_0_route0_11_08_16_39_17',
#@  'StaticCutIn/Town12_Rep0_2481_0_route0_11_08_20_24_25',
#@  'VehicleOpensDoorTwoWays/Town12_Rep0_2071_0_route0_11_08_11_38_46',
#@  'SignalizedJunctionLeftTurn/Town12_Rep0_2790_0_route0_11_09_03_19_21',
#@  'OppositeVehicleTakingPriority/Town12_Rep0_1644_1_route0_11_09_10_11_38',
#@  'SignalizedJunctionLeftTurn/Town12_Rep0_700_0_route0_11_08_22_04_21',
#@  'MergerIntoSlowTrafficV2/Town12_Rep0_968_39_route0_11_08_17_30_50',
#@  'MergerIntoSlowTrafficV2/Town12_Rep0_968_18_route0_11_09_01_36_13',
#@  'ConstructionObstacleTwoWays/Town12_Rep0_4437_1_route0_11_08_06_49_29',
#@  'SignalizedJunctionLeftTurn/Town12_Rep0_2815_0_route0_11_08_16_57_59',
#@  'ControlLoss/Town12_Rep0_3014_0_route0_11_09_06_10_10',
#@  'ConstructionObstacle/Town12_Rep0_2879_0_route0_11_08_23_40_32',
#@  'ParkedObstacle/Town12_Rep0_3744_0_route0_11_08_06_08_58',
#@  'BlockedIntersection/Town12_Rep0_2399_0_route0_11_09_00_56_08',
#@  'HighwayCutIn/Town12_Rep0_4013_4_route0_11_09_02_32_56',
#@  'VehicleTurningRoutePedestrian/Town12_Rep0_538_0_route0_11_08_12_19_10',
#@  'ParkingCutIn/Town12_Rep0_170_0_route0_11_08_22_01_27',
#@  'NonSignalizedJunctionLeftTurn/Town12_Rep0_1815_0_route0_11_09_05_16_18',
#@  'CrossingBicycleFlow/Town12_Rep0_4254_2_route0_11_08_03_51_42',
#@  'ControlLoss/Town12_Rep0_1928_0_route0_11_09_12_07_11',
#@  'ParkingCrossingPedestrian/Town12_Rep0_162_1_route0_11_09_02_22_55',
#@  'BlockedIntersection/Town12_Rep0_1509_0_route0_11_08_03_28_39',
#@  'ParkingExit/Town12_Rep0_2667_1_route0_11_08_08_00_43',
#@  'HighwayExit/Town12_Rep0_4136_2_route0_11_09_06_17_21',
#@  'ControlLoss/Town12_Rep0_241_0_route0_11_08_15_11_30',
#@  'VehicleTurningRoute/Town12_Rep0_3274_0_route0_11_09_03_05_57',
#@  'Accident/Town12_Rep0_4513_1_route0_11_08_18_56_45',
#@  'ParkingCrossingPedestrian/Town12_Rep0_566_0_route0_11_09_05_19_16',
#@  'DynamicObjectCrossing/Town12_Rep0_781_0_route0_11_09_05_02_07',
#@  'VehicleTurningRoute/Town12_Rep0_4205_1_route0_11_09_04_34_12',
#@  'EnterActorFlow/Town12_Rep0_2584_2_route0_11_08_05_02_11',
#@  'VehicleTurningRoute/Town12_Rep0_3168_0_route0_11_08_22_14_17',
#@  'HighwayCutIn/Town12_Rep0_4013_0_route0_11_08_00_17_03',
#@  'SignalizedJunctionLeftTurn/Town12_Rep0_1002_0_route0_11_09_02_51_45',
#@  'HighwayCutIn/Town12_Rep0_2954_1_route0_11_09_01_19_08',
#@  'ConstructionObstacleTwoWays/Town12_Rep0_1224_0_route0_11_09_08_55_42',
#@  'DynamicObjectCrossing/Town12_Rep0_3900_0_route0_11_08_02_48_11',
#@  'HazardAtSideLaneTwoWays/Town12_Rep0_4463_0_route0_11_08_01_53_39',
#@  'InterurbanAdvancedActorFlow/Town12_Rep0_1289_1_route0_11_08_08_03_49',
#@  'HighwayExit/Town12_Rep0_4521_10_route0_11_08_11_48_50',
#@  'NonSignalizedJunctionRightTurn/Town12_Rep0_3185_0_route0_11_08_21_56_42',
#@  'OppositeVehicleRunningRedLight/Town12_Rep0_2155_0_route0_11_09_00_48_09',
#@  'Accident/Town12_Rep0_1334_1_route0_11_09_10_20_37',
#@  'PedestrianCrossing/Town12_Rep0_94_0_route0_11_08_01_31_09',
#@  'PriorityAtJunction/Town12_Rep0_2342_0_route0_11_09_07_10_16',
#@  'InterurbanActorFlow/Town12_Rep0_3462_0_route0_11_08_07_37_17',
#@  'HardBreakRoute/Town12_Rep0_954_0_route0_11_08_00_55_35',
#@  'SignalizedJunctionRightTurn/Town12_Rep0_1179_0_route0_11_08_21_35_52',
#@  'VehicleTurningRoute/Town12_Rep0_1702_0_route0_11_08_16_25_46',
#@  'YieldToEmergencyVehicle/Town12_Rep0_2453_0_route0_11_09_04_32_32',
#@  'MergerIntoSlowTrafficV2/Town12_Rep0_968_29_route0_11_09_06_05_31',
#@  'ControlLoss/Town12_Rep0_1988_0_route0_11_09_02_32_17',
#@  'OppositeVehicleTakingPriority/Town12_Rep0_2869_1_route0_11_08_06_25_17',
#@  'VehicleTurningRoutePedestrian/Town12_Rep0_2057_0_route0_11_08_22_42_35',
#@  'EnterActorFlowV2/Town12_Rep0_975_5_route0_11_08_13_28_32',
#@  'CrossingBicycleFlow/Town12_Rep0_684_0_route0_11_08_12_36_03',
#@  'EnterActorFlow/Town12_Rep0_961_2_route0_11_08_11_36_12',
#@  'ParkingExit/Town12_Rep0_4469_2_route0_11_08_06_51_01',
#@  'HazardAtSideLaneTwoWays/Town12_Rep0_3514_0_route0_11_08_14_59_48'
#@ ]

#@ cameras = [
#@     'rgb',
#@ ]
---
_target_: rbyte.Dataset
_recursive_: false
_convert_: all
sources:
  #@ for input_id in drives:
  (@=input_id@):
    #@ for source_id in cameras:
    (@=source_id@):
      index_column: meta._idx_
      source:
        _target_: rbyte.io.PathTensorSource
        path: '${paths.data_dir}/(@=input_id@)/(@=source_id@)/{:04d}.jpg'
        decoder:
          _target_: simplejpeg.decode_jpeg
          _partial_: true
          colorspace: rgb
          fastdct: true
          fastupsample: true

    #@ end
  #@ end

samples:
  inputs:
    #@ for input_id in drives:
    (@=input_id@):
      measurements_path: ${paths.data_dir}/(@=input_id@)/measurements.json
      waypoints_path: ${paths.data_dir}/(@=input_id@)/waypoints.json
    #@ end

  executor:
    _target_: concurrent.futures.ThreadPoolExecutor

  storage: dict
  pipeline:
    _target_: pipefunc.Pipeline
    validate_type_annotations: false
    functions:
      - _target_: pipefunc.PipeFunc
        renames:
          path: measurements_path
        output_name: logs
        mapspec: "measurements_path[i] -> logs[i]"
        func:
          _target_: rbyte.io.JsonDataFrameBuilder
          fields:
            records:
              speed: 
              steer:
              throttle:
              brake:
                _target_: polars.Float32 # in data it's just 0 and 1
              pos_global:
                _target_: polars.Array
                inner:
                  _target_: polars.Float32
                shape: 2

      - _target_: pipefunc.PipeFunc
        renames:
          input: logs
        output_name: data_logs
        mapspec: "logs[i] -> data_logs[i]"
        func:
          _target_: rbyte.io.DataFrameConcater
          method: vertical 

      - _target_: pipefunc.PipeFunc
        renames:
          input: data_logs
        output_name: meta
        mapspec: "data_logs[i] -> meta[i]"
        func:
          _target_: rbyte.io.DataFrameIndexer
          name: _idx_                
      
      - _target_: pipefunc.PipeFunc
        renames:
          path: waypoints_path
        output_name: features
        output_picker:
          _target_: hydra.utils.get_method
          path: builtins.dict.get
        mapspec: "waypoints_path[i] -> features[i]"
        func:
          _target_: rbyte.io.JsonDataFrameBuilder
          fields:
            features:
              properties.timestamp:
              properties.heading:
              geometry.coordinates:
                _target_: polars.Array
                inner:
                  _target_: polars.Float32
                shape: 2
        
      - _target_: pipefunc.PipeFunc
        renames:
          input: features
        output_name: waypoints
        mapspec: "features[i] -> waypoints[i]"
        func:
          _target_: rbyte.io.CarlaGarageWaypointPreprocessor
          num_waypoints: 10
          columns:
            timestamp: properties.timestamp
            heading: properties.heading
            coordinates: geometry.coordinates
            output: waypoints

      - _target_: pipefunc.PipeFunc
        output_name: data
        mapspec: "meta[i], waypoints[i] -> data[i]"
        func:
          _target_: pipefunc.helpers.collect_kwargs
          parameters: [meta, waypoints]
          function_name: aggregate
        
      - _target_: pipefunc.PipeFunc
        renames:
          input: data
        output_name: aligned
        mapspec: "data[i] -> aligned[i]"
        func:
          _target_: rbyte.io.DataFrameAligner
          separator: .
          fields:
            meta:
              key: _idx_
              columns:
                records.speed:
                  method: interp
                records.steer:
                  method: interp
                records.throttle:
                  method: interp
                records.brake:
                  method: interp
                records.pos_global:
                  method: asof
                  strategy: nearest

            waypoints:
              key: properties.timestamp
              columns:
                properties.heading:
                  method: asof
                  strategy: nearest
                waypoints:
                  method: asof

      - _target_: pipefunc.PipeFunc
        renames:
          input: aligned
        output_name: with_waypoints_normalized
        mapspec: "aligned[i] -> with_waypoints_normalized[i]"
        func:
          _target_: rbyte.io.CarlaGarageWaypointNormalizer
          columns:
            ego_coordinates: meta.pos_global
            waypoint_coordinates: waypoints.waypoints
            heading: waypoints.properties.heading
            output: waypoints.waypoints_normalized
      
      - _target_: pipefunc.PipeFunc
        renames:
          input: with_waypoints_normalized
        output_name: samples
        mapspec: "with_waypoints_normalized[i] -> samples[i]"
        func:
          _target_: rbyte.io.FixedWindowSampleBuilder
          index_column: meta._idx_
          every: 1i
          period: 7i
          closed: both
          gather_every: 1
          length: 8