#@ drives = [
#@    'Niro096-HQ/2023-01-11--13-47-36',
#@    'Niro101-HQ/2022-12-25--09-58-33',
#@    'Niro101-HQ/2022-12-30--09-23-51',
#@    'Niro101-HQ/2022-12-31--09-57-24',
#@    'Niro101-HQ/2023-01-01--09-31-43',
#@    'G1-00428/2024-04-23--07-00-31',
#@    'Niro104-HQ/2023-04-27--08-23-53',
#@    'G1-00429/2024-04-22--13-35-09',
#@    'G1-00436/2024-04-22--07-48-38',
#@    'G1-00436/2024-04-22--15-59-18',
#@    'Niro115-HQ/2023-05-16--10-47-33',
#@    'Niro104-HQ/2022-12-20--13-57-20',
#@    'Niro107-HQ/2023-05-12--12-05-15',
#@    'Niro122-HQ/2023-04-05--12-06-39',
#@    'Niro102-HQ/2022-12-03--11-30-20',
#@ ]
#@ cameras = ['cam_front_left']
#@

_target_: yaak_datasets.Dataset
_recursive_: false
config:
  data:
    drives:
      #@ for drive in drives:
      - id: #@ drive
        sources:
          #@ for camera in cameras:
          - camera: #@ camera
            reader:
              _target_: yaak_datasets.FrameImageVideoReader
              path: "${paths.data_dir}/${....id}/frames/${..camera}.defish.mp4/576x324/{:09d}.jpg"
          #@ end
        metadata:
          path: ${paths.data_dir}/${..id}/metadata.log
      #@ end

    metadata:
      cameras: #@ cameras
      select: ???
      filter: ???

  samples:
    alignment:
      ref_camera: #@ cameras[0]
      tolerance: 10ms

    clips: ???
    transforms: ???

  processing:
    max_workers: !!null
    metadata:
      cache:
        enabled: true
        path: ${paths.metadata_cache_dir}
        size_limit: "1 GiB"
