_target_: rmind.models.action_tokenizer.ActionTokenizer
_recursive_: false
_convert_: all


input_transform:
  _target_: torch.nn.Sequential
  _convert_: all
  _args_:
    - _target_: rmind.components.nn.Remapper
      paths:
        continuous:
          gas_pedal: [data, meta/VehicleMotion/gas_pedal_normalized]
          brake_pedal: [data, meta/VehicleMotion/brake_pedal_normalized]
          steering_angle: [data, meta/VehicleMotion/steering_angle_normalized]
        discrete:
          turn_signal: [data, meta/VehicleState/turn_signal]
    - _target_: rmind.components.containers.ModuleDict
      modules:
        continuous:
          _target_: rmind.components.nn.Identity
        discrete:
          turn_signal:
            # turn_signal {OFF, LEFT, RIGHT} == {0, 1, 2} → {0.0, 0.5, 1.0}
            _target_: rmind.components.norm.Scaler
            in_range: [0.0, 2.0]
            out_range: [0.0, 1.0]

encoder:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: rmind.components.nn.Linear
      in_features: ${action_dim}
      out_features: ${action_hidden_dim}
    - _target_: torch.nn.GELU
    - _target_: rmind.components.nn.Linear
      in_features: ${action_hidden_dim}
      out_features: ${action_latent_dim}

quantizer:
  _target_: rmind.components.vq.ResidualVQ
  dim: ${action_latent_dim}
  codebook_size: ${codebook_size}
  num_quantizers: ${num_quantizers}

decoder:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: rmind.components.nn.Linear
      in_features: ${action_latent_dim}
      out_features: ${action_hidden_dim}
    - _target_: torch.nn.GELU
    - _target_: rmind.components.nn.Linear
      in_features: ${action_hidden_dim}
      out_features: ${action_dim}

targets:
  continuous:
    gas_pedal: [continuous, gas_pedal]
    brake_pedal: [continuous, brake_pedal]
    steering_angle: [continuous, steering_angle]
  discrete:
    turn_signal: [discrete, turn_signal]

commitment_weight: 1.0
vq_weight: 5.0

optimizer:
  _target_: rmind.components.optimizers.SelectiveAdamW
  _recursive_: true
  lr: 5.5e-5
  betas: [0.9, 0.95]
  weight_decay: 0.1
  weight_decay_module_blacklist:
    - _target_: hydra.utils.get_class
      path: torch.nn.Embedding
    - _target_: hydra.utils.get_class
      path: torch.nn.LayerNorm

lr_scheduler:
  interval: step
  scheduler:
    _target_: rmind.components.lr_schedulers.get_cosine_schedule_with_warmup
    num_warmup_steps: 2500
    num_training_steps: 50000
